import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

interface DrinkImageManifestEntry {
  slug: string;
  code?: string | null;
  displayName: string;
  category: string;
  status: string;
  assets?: {
    tv?: string;
    [key: string]: string | undefined;
  };
}

const repoRoot = process.cwd();
const assetRepoRoot = path.join(repoRoot, 'vendor', 'tearekz-drink-images');
const manifestPath = path.join(assetRepoRoot, 'manifest', 'drinks.json');
const outputDir = path.join(repoRoot, 'public', 'images', 'drinks', 'showcase');
const dataOutputPath = path.join(repoRoot, 'src', 'data', 'drink-images', 'showcaseImages.ts');

if (!existsSync(manifestPath)) {
  if (existsSync(dataOutputPath) && existsSync(outputDir)) {
    console.warn(
      'Drink image submodule is unavailable; using committed generated showcase assets.'
    );
    process.exit(0);
  }

  throw new Error(
    `Missing ${path.relative(repoRoot, manifestPath)}. Run git submodule update --init --recursive.`
  );
}

const raw = readFileSync(manifestPath, 'utf8');
const manifest = JSON.parse(raw) as DrinkImageManifestEntry[];
const cutouts = manifest.filter((entry) => entry.status === 'cutout' && entry.assets?.tv);

rmSync(outputDir, { recursive: true, force: true });
mkdirSync(outputDir, { recursive: true });
mkdirSync(path.dirname(dataOutputPath), { recursive: true });

const images = cutouts.map((entry) => {
  const sourceRelativePath = entry.assets?.tv;
  if (!sourceRelativePath) {
    throw new Error(`Missing tv asset for ${entry.slug}`);
  }

  const sourcePath = path.join(assetRepoRoot, sourceRelativePath);
  const fileName = path.basename(sourceRelativePath);
  const outputPath = path.join(outputDir, fileName);
  copyFileSync(sourcePath, outputPath);

  return {
    name: entry.displayName,
    alt: `${entry.displayName} drink preview`,
    category: entry.category,
    src: `/images/drinks/showcase/${fileName}`,
  };
});

const ts =
  `// Generated by src/scripts/drink-images/sync-drink-images.ts\n` +
  `// Source: vendor/tearekz-drink-images/manifest/drinks.json\n\n` +
  `export const SHOWCASE_IMAGES = ${JSON.stringify(images, null, 2)} as const;\n` +
  `export type ShowcaseImage = (typeof SHOWCASE_IMAGES)[number];\n`;

writeFileSync(dataOutputPath, ts);
console.log(
  `Synced ${images.length} drink showcase images to ${path.relative(repoRoot, outputDir)}`
);
